// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/26/2025, 10:33:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mac/Dev/my-projects/friendnet-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/plugins/**/*.{js,ts,mjs}","/Users/mac/Dev/my-projects/friendnet-app/composables/**/*.{js,ts,mjs}","/Users/mac/Dev/my-projects/friendnet-app/utils/**/*.{js,ts,mjs}","/Users/mac/Dev/my-projects/friendnet-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Dev/my-projects/friendnet-app/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"ai-primary":{"50":"#f0f9ff","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","900":"#1e3a8a"},"ai-accent":{"500":"#8b5cf6","600":"#7c3aed"},"ai-dark":{"800":"#1f2937","900":"#111827"}},"animation":{"pulse-glow":"pulse-glow 2s ease-in-out infinite alternate","float":"float 3s ease-in-out infinite","scan":"scan 2s linear infinite"},"keyframes":{"pulse-glow":{"from":{"boxShadow":"0 0 20px #3b82f6"},"to":{"boxShadow":"0 0 40px #3b82f6, 0 0 60px #3b82f6"}},"float":{"0%, 100%":{"transform":"translateY(0px)"},"50%":{"transform":"translateY(-10px)"}},"scan":{"0%":{"transform":"translateX(-100%)"},"100%":{"transform":"translateX(100%)"}}}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;